### ISSUE TITLE
Windows unauthorized app warning

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#13] opened 2016-02-19 15:46 UTC
There's an unrecognized app warning on windows when the tool launches, and you must "run anyway" in order to bypass it.  Can we eliminate this?

**Comment by jlucidar** [comment] 2016-02-22 21:49
@ryansturmer , you mean this one ? 
![image](https://cloud.githubusercontent.com/assets/7430482/13233895/4c503bc4-d9b6-11e5-83fd-9c2eb2e6bf53.png)
It's a normal reaction and we can't eliminate it.
If it's not this one, I'm not able to reproduce though...
Closing this one as it may have been resolves with the installer.

**Closed as completed by jlucidar** 2016-02-22 21:49 UTC
